### ISSUE TITLE
Testing / packaging roundcube-next

### ISSUE THREAD

**Issue by src386** [roundcube-next/roundcube-mail#1]
Hi,
I'm interested in testing roundcube-next, even packaging for Yunohost project.
But there it seems there is no documentation right now.
How is it working ? What components do I need to install ? roundcube-server + roundcube-email ?
Thanks.

**Comment by kanarip** [comment]
Note that this a project in development.

Please see [the installation instructions for Roundcube Shell](https://github.com/roundcube-next/roundcube-shell/blob/master/README.md)
